version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"

  nginx:
    image: nginx:latest
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
